# databases:
#   - name: mysite-db
#     databaseName: mysite
#     user: mysiteuser
#     plan: free

# services:
#   - type: web
#     name: mysite-web
#     env: python
#     plan: free
#     buildCommand: "./build.sh"
#     startCommand: "gunicorn mysite.wsgi:application"
#     envVars:
#       - key: DATABASE_URL
#         fromDatabase:
#           name: mysite-db
#           property: connectionString
#       - key: SECRET_KEY
#         generateValue: true
#       - key: WEB_CONCURRENCY
#         value: 4
services:
  - type: web
    name: mysite-web
    env: python
    plan: free
    rootDir: mysite
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application --bind 0.0.0.0:$PORT"